version: "3"
services:
  api:
    container_name: store-api
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db

volumes:
  data:
