version: "3.8"
services:
  api:
    container_name: store-api
    build: .
    image: storeapi
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4
    ports:
      - 27018:27017
    volumes:
      - data:/data/db

volumes:
  data:
    name: mongodb-data
